import http from 'node:http';
import {createHash,createHmac,randomBytes,randomUUID,scryptSync,timingSafeEqual} from 'node:crypto';
import {readFile,stat,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {openDb,getProducts,getSettings,getOrder} from './db.mjs';
import {calculateQuote,customerInput,productInput,textValue,fail} from './commerce.mjs';
import {readiness,settingsInput,deliveryCheck,changeStock,releaseStock,applyRefund,queueOrderMail} from './operations.mjs';
import {pageMetadata,discoveryResponse} from './pages.mjs';
const digest=v=>createHash('sha256').update(v).digest('hex');
const equal=(a,b)=>{if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);};
const hmac=(secret,message)=>createHmac('sha256',secret).update(message).digest('hex');
export function createApp({db=openDb(),env=process.env,gatewayFetch=fetch}={}){
 const production=env.NODE_ENV==='production',root=resolve('Template'),origin=env.APP_ORIGIN||'http://localhost:3000';
 if(production&&!/^https:\/\//.test(origin))throw new Error('Set APP_ORIGIN to the HTTPS store origin in production.');
 const hasKeys=()=>!!(env.RAZORPAY_KEY_ID&&env.RAZORPAY_KEY_SECRET&&env.RAZORPAY_WEBHOOK_SECRET);
 const limits=new Map();
 function limited(req,scope,max){const ip=env.TRUST_PROXY==='1'?req.headers['x-real-ip']||req.socket.remoteAddress:req.socket.remoteAddress;const key=scope+':'+ip,now=Date.now();let b=limits.get(key);if(!b||b.until<now){b={count:0,until:now+900000};limits.set(key,b);}if(++b.count>max)fail('Too many attempts. Please try again in 15 minutes.',429);if(limits.size>5000){for(const [k,v] of limits)if(v.until<now)limits.delete(k);if(limits.size>10000)limits.delete(limits.keys().next().value);}}
 function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
 async function body(req,maximum=65536){let chunks=[],length=0;for await(const c of req){length+=c.length;if(length>maximum)fail('Request is too large.',413);chunks.push(c);}return Buffer.concat(chunks);}
 function json(raw){try{const v=JSON.parse(raw.toString());if(!v||typeof v!=='object'||Array.isArray(v))fail('Expected a JSON object.');return v;}catch(e){if(e.status)throw e;fail('Invalid request.');}}
 function admin(req){const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('zaman_admin='))?.slice(12);const session=cookie&&db.prepare('SELECT expires FROM sessions WHERE token_hash=?').get(digest(cookie));if(!session||session.expires<Date.now())fail('Please sign in to manage your store.',401);return cookie;}
 function owned(req,id){const row=db.prepare('SELECT token FROM orders WHERE id=?').get(id);if(!row||!equal(row.token,req.headers['x-order-token']))fail('Order not found. Please use your private order link.',404);return getOrder(db,id);}
 async function gateway(path,method='GET',payload){if(!hasKeys())fail('Online payments are unavailable. Please choose another payment method.',503);const r=await gatewayFetch('https://api.razorpay.com/v1/'+path,{method,headers:{Authorization:'Basic '+Buffer.from(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET).toString('base64'),'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined,signal:AbortSignal.timeout(20000)});if(!r.ok)fail('The payment provider could not complete this request. Please try again.',502);return r.json();}
 function markPaid(id,payment){const o=getOrder(db,id);if(!o)fail('Order not found.',404);if(payment.order_id!==o.razorpayOrderId||payment.amount!==o.total||payment.currency!=='INR'||payment.status!=='captured')fail('Payment has not been confirmed for this order.');if(o.razorpayPaymentId&&o.razorpayPaymentId!==payment.id)fail('Another payment is already linked to this order.',409);if(['partially_refunded','refunded'].includes(o.paymentStatus))return o;db.prepare("UPDATE orders SET payment_status='paid',razorpay_payment_id=?,status=CASE WHEN status='pending_payment' THEN 'confirmed' ELSE status END WHERE id=?").run(payment.id,id);queueOrderMail(db,id,'paid');return getOrder(db,id);}
 const pendingPayments=new Map();
 async function initiatePayment(o){if(o.razorpayOrderId)return o.razorpayOrderId;if(pendingPayments.has(o.id))return pendingPayments.get(o.id);const job=(async()=>{const latest=getOrder(db,o.id);if(latest.razorpayOrderId)return latest.razorpayOrderId;const r=await gateway('orders','POST',{amount:o.total,currency:'INR',receipt:o.number,notes:{zaman_order_id:o.id}});if(!r.id||r.amount!==o.total||r.currency!=='INR')fail('Payment provider returned an invalid order.',502);db.prepare('UPDATE orders SET razorpay_order_id=? WHERE id=?').run(r.id,o.id);return r.id;})();pendingPayments.set(o.id,job);try{return await job;}finally{pendingPayments.delete(o.id);}}
 const server=http.createServer(async(req,res)=>{
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
 res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' https://checkout.razorpay.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.razorpay.com; font-src 'self'; connect-src 'self' https://*.razorpay.com; frame-src https://*.razorpay.com https://api.razorpay.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");
 if(production)res.setHeader('Strict-Transport-Security','max-age=31536000');
 try{
 const url=new URL(req.url,'http://localhost'),path=url.pathname,method=req.method;
 if(path==='/api/health'&&method==='GET'){db.prepare('SELECT 1').get();return send(res,200,{ok:true});}
 if(discoveryResponse(req,res,path,origin))return;
 if(path.startsWith('/api/')){
 const webhook=path==='/api/payments/webhook';
 if(!['GET','HEAD','OPTIONS'].includes(method)&&!webhook){if(req.headers.origin!==origin)fail('This request must come from the store.',403);if(!req.headers['content-type']?.startsWith('application/json'))fail('Use JSON for this request.',415);}
 if(path==='/api/catalog'&&method==='GET'){const s=getSettings(db);if(!s.policiesReviewed)for(const key of ['shippingPolicy','returnsPolicy','privacyPolicy','termsPolicy'])delete s[key];return send(res,200,{products:getProducts(db).filter(p=>p.active),settings:{...s,onlineAvailable:hasKeys()}});}
 if(path==='/api/quote'&&method==='POST'){limited(req,'quote',500);const b=json(await body(req)),q=calculateQuote(db,b.items),s=getSettings(db);if(b.pincode)deliveryCheck(s,b.pincode,b.paymentMethod);const codFee=b.paymentMethod==='cod'?(s.codFee||0):0;return send(res,200,{...q,codFee,total:q.total+codFee});}
 if(path==='/api/delivery'&&method==='POST'){limited(req,'quote',500);const b=json(await body(req)),s=getSettings(db);deliveryCheck(s,b.pincode,b.paymentMethod);return send(res,200,{available:true,summary:s.deliverySummary,codAvailable:s.codEnabled&&(!s.codPincodes?.length||s.codPincodes.includes(b.pincode))});}
 if(path==='/api/orders'&&method==='POST'){
 limited(req,'order',35);const b=json(await body(req)),key=req.headers['idempotency-key'];if(typeof key!=='string'||!/^[a-zA-Z0-9-]{16,100}$/.test(key))fail('Please retry checkout.');const customer=customerInput(b.customer);if(!['online','cod'].includes(b.paymentMethod))fail('Choose a valid payment method.');const fingerprint=digest(JSON.stringify({items:b.items,customer,paymentMethod:b.paymentMethod,expectedTotal:b.expectedTotal}));const previous=db.prepare('SELECT id,token,fingerprint FROM orders WHERE idem=?').get(key);if(previous){if(previous.fingerprint!==fingerprint)fail('This checkout attempt has changed. Please try again.',409);return send(res,200,{...getOrder(db,previous.id),accessToken:previous.token});}
 const s=getSettings(db);deliveryCheck(s,customer.pincode,b.paymentMethod);if(b.acceptedTerms!==true)fail('Please accept the purchase terms.');if(b.paymentMethod==='cod'&&!s.codEnabled)fail('Cash on delivery is currently unavailable.');if(b.paymentMethod==='online'&&!hasKeys())fail('Online payments are currently unavailable.',503);const q=calculateQuote(db,b.items);q.codFee=b.paymentMethod==='cod'?(s.codFee||0):0;q.total+=q.codFee;if(!Number.isInteger(b.expectedTotal)||q.total!==b.expectedTotal)fail('Prices or delivery charges changed. Refresh your bag and review the new total.',409);const id=randomUUID(),token=randomBytes(32).toString('hex'),number='ZT-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+randomBytes(4).toString('hex').toUpperCase(),createdAt=new Date().toISOString();db.exec('BEGIN IMMEDIATE');try{changeStock(db,q.items,-1);db.prepare('INSERT INTO orders (id,number,token,idem,fingerprint,created_at,status,payment_status,payment_method,data) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,number,token,key,fingerprint,createdAt,b.paymentMethod==='cod'?'confirmed':'pending_payment',b.paymentMethod==='cod'?'unpaid':'pending',b.paymentMethod,JSON.stringify({...q,customer,courier:'',trackingNumber:'',trackingUrl:'',stockReserved:true,stockRestored:false,everShipped:false,termsAcceptedAt:createdAt,policyVersion:s.policyVersion,seller:{name:s.businessName,address:s.businessAddress,email:s.supportEmail}}));queueOrderMail(db,id,'created');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return send(res,201,{...getOrder(db,id),accessToken:token});
 }
 const orderRoute=path.match(/^\/api\/orders\/([a-f0-9-]{36})(?:\/(payment|verify))?$/);
 if(orderRoute){limited(req,'orderAccess',200);const id=orderRoute[1],action=orderRoute[2],o=owned(req,id);if(!action&&method==='GET')return send(res,200,o);
 if(action==='payment'&&method==='POST'){if(o.paymentMethod!=='online'||o.status==='cancelled')fail('This order cannot accept an online payment.');if(['paid','partially_refunded','refunded'].includes(o.paymentStatus))return send(res,200,{alreadyPaid:true});const razorpayOrderId=await initiatePayment(o);return send(res,200,{keyId:env.RAZORPAY_KEY_ID,amount:o.total,razorpayOrderId,prefill:{name:o.customer.name,contact:'+91'+o.customer.phone,email:o.customer.email}});}
 if(action==='verify'&&method==='POST'){const b=json(await body(req));if(!o.razorpayOrderId||b.razorpay_order_id!==o.razorpayOrderId||typeof b.razorpay_payment_id!=='string'||!/^pay_[a-zA-Z0-9]+$/.test(b.razorpay_payment_id)||!equal(hmac(env.RAZORPAY_KEY_SECRET||'',o.razorpayOrderId+'|'+b.razorpay_payment_id),b.razorpay_signature))fail('Payment verification failed.',400);const payment=await gateway('payments/'+b.razorpay_payment_id);if(payment.order_id!==o.razorpayOrderId||payment.amount!==o.total||payment.currency!=='INR')fail('Payment does not match this order.');if(payment.status==='captured')return send(res,200,markPaid(id,payment));return send(res,200,{paymentStatus:'pending'});}
 }
 if(webhook&&method==='POST'){if(!env.RAZORPAY_WEBHOOK_SECRET)fail('Webhook unavailable.',503);const raw=await body(req);if(!equal(hmac(env.RAZORPAY_WEBHOOK_SECRET,raw),req.headers['x-razorpay-signature']))fail('Invalid signature.',400);const event=json(raw),eventId=String(req.headers['x-razorpay-event-id']||digest(raw));if(db.prepare('SELECT id FROM webhook_events WHERE id=?').get(eventId))return send(res,200,{received:true});db.exec('BEGIN IMMEDIATE');try{if(event.event==='payment.captured'){const p=event.payload?.payment?.entity;const r=p?.order_id&&db.prepare('SELECT id FROM orders WHERE razorpay_order_id=?').get(p.order_id);if(r)markPaid(r.id,p);}if(['refund.created','refund.processed','refund.failed'].includes(event.event)){const id=applyRefund(db,event.payload?.refund?.entity);if(id)queueOrderMail(db,id,event.event+':'+event.payload.refund.entity.id);}db.prepare('INSERT INTO webhook_events VALUES (?,?)').run(eventId,new Date().toISOString());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return send(res,200,{received:true});}
 if(path==='/api/admin/login'&&method==='POST'){limited(req,'login',10);const b=json(await body(req)),a=db.prepare('SELECT * FROM admin WHERE id=1').get();if(typeof b.password!=='string'||b.password.length>256)fail('Invalid sign-in details.',401);const hash=scryptSync(b.password,a?.salt||'zaman-no-admin-yet',64).toString('hex');if(!a||typeof b.email!=='string'||b.email.trim().toLowerCase()!==a.email||!equal(hash,a.hash))fail('Invalid sign-in details.',401);const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires < ?').run(Date.now());db.prepare('INSERT INTO sessions VALUES (?,?)').run(digest(token),Date.now()+8*3600000);res.setHeader('Set-Cookie',`zaman_admin=${token}; HttpOnly; SameSite=Strict; Path=/api/admin; Max-Age=28800${production?'; Secure':''}`);return send(res,200,{email:a.email});}
 if(path.startsWith('/api/admin/')){const session=admin(req);
 if(path==='/api/admin/readiness'&&method==='GET')return send(res,200,{issues:readiness(db),mailConfigured:!!(env.SMTP_HOST&&env.MAIL_FROM),mailPending:db.prepare('SELECT count(*) AS n FROM mail_outbox WHERE sent_at IS NULL').get().n,mailFailed:db.prepare('SELECT count(*) AS n FROM mail_outbox WHERE sent_at IS NULL AND attempts>0').get().n});
 const refundRoute=path.match(/^\/api\/admin\/orders\/([a-f0-9-]{36})\/(refunds|restock)$/);if(refundRoute&&method==='POST'){const id=refundRoute[1],o=getOrder(db,id);if(!o)fail('Order not found.',404);if(refundRoute[2]==='restock'){if(!['cancelled','delivered'].includes(o.status)&&o.paymentStatus!=='refunded')fail('Only cancelled, returned or fully refunded orders can be restocked.');db.exec('BEGIN IMMEDIATE');try{releaseStock(db,id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}else{if(!o.razorpayPaymentId)fail('No online payment to reconcile.');const refunds=[];for(let skip=0;skip<10000;skip+=100){const result=await gateway('payments/'+o.razorpayPaymentId+'/refunds?count=100&skip='+skip);if(!Array.isArray(result.items))fail('Invalid refund response.',502);refunds.push(...result.items);if(result.items.length<100)break;if(skip===9900)fail('Too many refunds to synchronize.',502);}db.exec('BEGIN IMMEDIATE');try{for(const refund of refunds){if(refund.payment_id!==o.razorpayPaymentId)fail('Refund payment mismatch.');applyRefund(db,refund);}queueOrderMail(db,id,'refund-sync:'+getOrder(db,id).refundedAmount);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}return send(res,200,getOrder(db,id));}
 if(path==='/api/admin/session'&&method==='GET')return send(res,200,{email:db.prepare('SELECT email FROM admin WHERE id=1').get().email});
 if(path==='/api/admin/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE token_hash=?').run(digest(session));res.setHeader('Set-Cookie',`zaman_admin=; HttpOnly; SameSite=Strict; Path=/api/admin; Max-Age=0${production?'; Secure':''}`);return send(res,200,{ok:true});}
 if(path==='/api/admin/images'&&method==='POST'){const b=json(await body(req,6*1024*1024));if(typeof b.data!=='string')fail('Choose an image.');const bytes=Buffer.from(b.data,'base64');if(!bytes.length||bytes.length>4*1024*1024)fail('Images must be smaller than 4 MB.');let ext;if(bytes.subarray(0,3).equals(Buffer.from([255,216,255])))ext='jpeg';else if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ext='png';else if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')ext='webp';else fail('Use a JPEG, PNG or WebP image.');const path='img/zaman/'+randomUUID()+'.'+ext;await writeFile(resolve(root,path),bytes,{flag:'wx',mode:0o644});return send(res,201,{path});}
 if(path==='/api/admin/products'&&method==='GET')return send(res,200,{products:getProducts(db)});
 if(path==='/api/admin/products'&&method==='POST'){const p=productInput(json(await body(req))),old=db.prepare('SELECT data FROM products WHERE id=?').get(p.id);if(old){const previous=JSON.parse(old.data);if((previous.revision||'')!==p.revision)fail('This product or its stock changed. Close this editor and reload Products before saving.',409);for(const v of previous.variants)if(!p.variants.some(n=>n.size===v.size)){const reserved=db.prepare("SELECT 1 FROM orders,json_each(json_extract(orders.data,'$.items')) AS item WHERE json_extract(orders.data,'$.stockReserved')=1 AND COALESCE(json_extract(orders.data,'$.stockRestored'),0)=0 AND json_extract(item.value,'$.productId')=? AND json_extract(item.value,'$.size')=? LIMIT 1").get(p.id,v.size);if(reserved)fail('This pack size is referenced by orders. Set its stock to zero instead of removing it.');}}p.revision=randomUUID();try{await stat(resolve(root,p.image));}catch{fail('That image is not on the server. Add it to Template/img/zaman first.');}const fresh=db.prepare('SELECT data FROM products WHERE id=?').get(p.id);if((fresh?.data||'')!==(old?.data||''))fail('Stock changed while saving. Reload Products and retry.',409);db.prepare('INSERT INTO products VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(p.id,JSON.stringify(p));return send(res,200,{product:p});}
 if(path==='/api/admin/settings'&&method==='GET')return send(res,200,{...getSettings(db),onlineAvailable:hasKeys()});
 if(path==='/api/admin/settings'&&method==='PUT'){const b=json(await body(req,1024*1024));if(b.freeShippingThreshold!==null&&(!Number.isInteger(b.freeShippingThreshold)||b.freeShippingThreshold<0||b.freeShippingThreshold>10000000))fail('Enter a valid free delivery threshold.');if(typeof b.whatsappNumber!=='string'||!/^91[6-9]\d{9}$/.test(b.whatsappNumber))fail('Enter an Indian WhatsApp number starting with 91.');const s={...settingsInput(b,getSettings(db)),shippingConfigured:b.shippingConfigured===true,freeShippingThreshold:b.freeShippingThreshold,codEnabled:b.codEnabled===true,whatsappNumber:b.whatsappNumber};s.policyVersion=new Date().toISOString();db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(s));if(s.shippingConfigured){const issues=readiness(db);if(issues.length)fail('Before accepting orders: '+issues.join(' '));}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return send(res,200,{...s,onlineAvailable:hasKeys()});}
 if(path==='/api/admin/orders'&&method==='GET'){const page=Math.max(1,Math.min(100000,Number(url.searchParams.get('page'))||1)),search=(url.searchParams.get('search')||'').slice(0,100),status=url.searchParams.get('status')||'';const conditions=[],args=[];if(search){conditions.push("(number LIKE ? OR json_extract(data,'$.customer.name') LIKE ? OR json_extract(data,'$.customer.phone') LIKE ?)");args.push('%'+search+'%','%'+search+'%','%'+search+'%');}if(status){conditions.push('status=?');args.push(status);}const where=conditions.length?' WHERE '+conditions.join(' AND '):'';const count=db.prepare('SELECT count(*) AS n FROM orders'+where).get(...args).n;const rows=db.prepare('SELECT id FROM orders'+where+' ORDER BY created_at DESC LIMIT 30 OFFSET ?').all(...args,(page-1)*30);const stats=db.prepare("SELECT COUNT(*) AS orders,COALESCE(SUM(CASE WHEN payment_status IN ('paid','partially_refunded') THEN json_extract(data,'$.total')-COALESCE(json_extract(data,'$.refundedAmount'),0) ELSE 0 END),0) AS collected,SUM(CASE WHEN status IN ('confirmed','packed','shipped') THEN 1 ELSE 0 END) AS active FROM orders").get();return send(res,200,{orders:rows.map(r=>getOrder(db,r.id)),total:count,page,stats});}
 const adminOrder=path.match(/^\/api\/admin\/orders\/([a-f0-9-]{36})$/);if(adminOrder&&method==='PATCH'){const o=getOrder(db,adminOrder[1]);if(!o)fail('Order not found.',404);const b=json(await body(req)),transitions={pending_payment:[],confirmed:['packed','cancelled'],packed:['shipped','cancelled'],shipped:['delivered','cancelled'],delivered:[],cancelled:[]};if(b.status!==o.status&&!transitions[o.status]?.includes(b.status))fail('Choose the next delivery stage. Online orders require a verified payment before fulfilment.');if(b.status==='cancelled'&&['paid','partially_refunded'].includes(o.paymentStatus))fail('Refund this payment in Razorpay and synchronize refunds before cancelling.');const courier=textValue(b.courier||'','courier',0,100),trackingNumber=textValue(b.trackingNumber||'','tracking number',0,150),trackingUrl=textValue(b.trackingUrl||'','tracking URL',0,600);if(trackingUrl){let u;try{u=new URL(trackingUrl);}catch{fail('Enter a valid HTTPS tracking URL.');}if(u.protocol!=='https:'||u.username||u.password)fail('Use an HTTPS tracking URL.');}if(b.status==='shipped'&&(!courier||!trackingNumber))fail('Add the courier and tracking number before marking as shipped.');const row=db.prepare('SELECT data FROM orders WHERE id=?').get(o.id);db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE orders SET status=?,payment_status=?,data=? WHERE id=?').run(b.status,b.status==='delivered'&&o.paymentMethod==='cod'?'paid':o.paymentStatus,JSON.stringify({...JSON.parse(row.data),everShipped:JSON.parse(row.data).everShipped===true||b.status==='shipped'||o.status==='shipped',courier,trackingNumber,trackingUrl}),o.id);if(b.status==='cancelled'&&o.paymentMethod==='cod'&&o.status!=='shipped'&&!o.everShipped)releaseStock(db,o.id);queueOrderMail(db,o.id,'status:'+b.status+':'+trackingNumber);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return send(res,200,getOrder(db,o.id));}
 }
 fail('Not found.',404);
 }
 if(method!=='GET'&&method!=='HEAD')fail('Method not allowed.',405);
 const aliases={'/':'index.html','/shop':'menu.html','/about':'about.html','/contact':'contacts.html','/checkout':'checkout.html','/admin':'admin.html'};
 const relative=aliases[path]||decodeURIComponent(path).replace(/^\//,'');
 const pages=['index.html','menu.html','about.html','contacts.html','checkout.html','order.html','admin.html','policies.html'];
 if(!pages.includes(relative)&&!(/^(css|js|img\/zaman|fonts)\/[a-zA-Z0-9_./-]+$/.test(relative)))fail('Page not found.',404);
 const file=resolve(root,relative);if(!file.startsWith(root+sep)||relative.includes('..'))fail('Not found.',404);
 let content;try{content=await readFile(file);}catch{fail('Page not found.',404);}
 const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpeg':'image/jpeg','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.woff':'font/woff','.svg':'image/svg+xml'};
 if(extname(file)==='.html')content=pageMetadata(content.toString(),relative,origin,getSettings(db));
 res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':extname(file)==='.html'?'no-cache':'public, max-age=3600'});res.end(method==='HEAD'?undefined:content);
 }catch(e){if(!res.headersSent)send(res,e.status||500,{error:e.status?e.message:'Something went wrong. Please try again.'});else res.end();if(!e.status)console.error('Request failed:',e.name);}
 });
 server.requestTimeout=30000;server.headersTimeout=10000;return {server,db};
}
