import {getProducts,getSettings} from './db.mjs';
export function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
export function textValue(v,name,min=1,max=100){if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)fail(`Please enter a valid ${name}.`);return v.trim();}
export function calculateQuote(db,items,{requireShipping=true}={}){
 const settings=getSettings(db);if(requireShipping&&!settings.shippingConfigured)fail('Our delivery rates are being updated. Please contact us to order.',503);
 if(!Array.isArray(items)||!items.length||items.length>30)fail('Choose between 1 and 30 different tea packs.');
 const products=getProducts(db),merged=new Map();
 for(const i of items){if(!i||typeof i.productId!=='string'||typeof i.size!=='string'||!Number.isInteger(i.qty)||i.qty<1||i.qty>50)fail('Please check the quantities in your bag.');const key=i.productId+'|'+i.size;const current=merged.get(key);if(current){current.qty+=i.qty;if(current.qty>50)fail('Maximum 50 packs of each size per order.');}else merged.set(key,{productId:i.productId,size:i.size,qty:i.qty});}
 const resolved=[...merged.values()].map(i=>{const p=products.find(p=>p.id===i.productId&&p.active);const v=p?.variants.find(v=>v.size===i.size);if(!p||!v)fail('A tea or pack size is no longer available. Please update your bag.');if(!Number.isInteger(v.stock))fail('This pack is not yet available. Please contact us.',409);if(v.stock<i.qty)fail(`${p.name} ${i.size}g has only ${v.stock} packs available.`,409);return {...i,name:p.name,image:p.image,price:v.price,shipping:p.shipping};});
 const subtotal=resolved.reduce((s,i)=>s+i.price*i.qty,0),shipping=settings.freeShippingThreshold!==null&&subtotal>=settings.freeShippingThreshold?0:resolved.reduce((s,i)=>s+i.shipping*i.qty,0),total=subtotal+shipping;
 if(total>100000000)fail('Please contact us directly for an order this large.');return {items:resolved,subtotal,shipping,total,currency:'INR'};
}
export function customerInput(c){if(!c||typeof c!=='object')fail('Please enter your delivery details.');const name=textValue(c.name,'name',2,100),phone=textValue(c.phone,'mobile number',10,16).replace(/[ +()-]/g,'').replace(/^91(?=\d{10}$)/,'');if(!/^[6-9]\d{9}$/.test(phone))fail('Enter a valid 10-digit Indian mobile number.');const email=String(c.email||'').trim();if(email&&(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>150))fail('Enter a valid email address.');const pincode=textValue(c.pincode,'PIN code',6,6);if(!/^[1-9]\d{5}$/.test(pincode))fail('Enter a valid 6-digit PIN code.');return {name,phone,email,address:textValue(c.address,'street address',8,300),city:textValue(c.city,'city',2,80),state:textValue(c.state,'state',2,80),pincode,notes:textValue(c.notes||'','delivery note',0,500)};}
export function productInput(p){const id=textValue(p.id,'product ID',2,60);if(!/^[a-z0-9-]+$/.test(id))fail('Product ID must use lowercase letters, numbers and hyphens.');if(!/^#[a-fA-F0-9]{6}$/.test(p.color))fail('Choose a valid product colour.');const image=textValue(p.image,'image path',5,240);if(!/^img\/zaman\/[a-zA-Z0-9_.-]+\.(jpeg|jpg|png|webp)$/.test(image))fail('Use an image from img/zaman.');if(!Number.isInteger(p.shipping)||p.shipping<0||p.shipping>100000)fail('Delivery charge must be between ₹0 and ₹1,000.');if(!Array.isArray(p.variants)||!p.variants.length||p.variants.length>12)fail('Add 1–12 pack sizes.');const used=new Set();const variants=p.variants.map(v=>{if(!v||!/^\d{1,5}$/.test(v.size)||Number(v.size)<=0||used.has(v.size)||!Number.isInteger(v.price)||v.price<100||v.price>10000000)fail('Each pack needs a unique size and a price of at least ₹1.');if(v.stock!==null&&(!Number.isInteger(v.stock)||v.stock<0||v.stock>1000000))fail('Enter stock from 0 to 1,000,000, or leave unconfigured.');used.add(v.size);return {size:v.size,price:v.price,stock:v.stock};});return {id,revision:textValue(p.revision||'','product revision',0,100),...Object.fromEntries(['ingredients','brewing','storage','shelfLife'].map(k=>[k,textValue(p[k]||'',k,0,2000)])),name:textValue(p.name,'product name',2,100),description:textValue(p.description,'description',10,500),notes:textValue(p.notes,'flavour notes',2,100),color:p.color,image,shipping:p.shipping,active:p.active===true,variants};}
