import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,scryptSync,createHmac} from 'node:crypto';
import {openDb,getSettings} from './db.mjs';
import {calculateQuote} from './commerce.mjs';
import {createApp} from './app.mjs';
const db=openDb(':memory:'),origin='http://localhost:3000';
const env={APP_ORIGIN:origin,RAZORPAY_KEY_ID:'rzp_test_example',RAZORPAY_KEY_SECRET:'test-key-secret',RAZORPAY_WEBHOOK_SECRET:'test-webhook-secret'};
const customer={name:'Test Customer',phone:'9876543210',email:'test@example.com',address:'12 Example Road',city:'Udupi',state:'Karnataka',pincode:'576101',notes:''};
for(const row of db.prepare('SELECT * FROM products').all()){const p=JSON.parse(row.data);p.variants=p.variants.map(v=>({...v,stock:100}));Object.assign(p,{ingredients:'Test ingredients',brewing:'Test brewing',storage:'Test storage',shelfLife:'Test shelf life'});db.prepare('UPDATE products SET data=? WHERE id=?').run(JSON.stringify(p),p.id);}
const settings={...getSettings(db),businessName:'Test Store',businessAddress:'Test address',supportEmail:'test@example.com',supportHours:'Test hours',deliverySummary:'Test delivery',shippingPolicy:'Test shipping policy',returnsPolicy:'Test returns policy',privacyPolicy:'Test privacy policy',termsPolicy:'Test terms policy',policiesReviewed:true,coverageReviewed:true,allIndia:true,deliveryPincodes:[],codPincodes:[],codFee:0};db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(settings));
const items=[{productId:'ginger',size:'150',qty:1}];
let base,cookie,codOrder,onlineOrder;
let gatewayCount=0;
const gatewayOrders=new Map();
const gatewayFetch=async(url,opts)=>{if(url.endsWith('/orders')&&opts.method==='POST'){gatewayCount++;const b=JSON.parse(opts.body),id='order_Test'+gatewayCount;gatewayOrders.set(id,b);return {ok:true,json:async()=>({id,...b})};}if(url.includes('/payments/pay_'))return {ok:true,json:async()=>({id:'pay_Test',order_id:onlineOrder.razorpayOrderId,amount:onlineOrder.total,currency:'INR',status:'captured'})};throw Error('Unexpected payment request');};
const {server}=createApp({db,env,gatewayFetch});
before(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();});
async function call(path,method='GET',body,headers={}){const r=await fetch(base+'/api'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(path==='/orders'?{acceptedTerms:true,...body}:body)});return {status:r.status,data:await r.json(),headers:r.headers};}
function shipping(value=true){const s=getSettings(db);s.shippingConfigured=value;db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(s));}
test('catalogue preserves original prices; unapproved shipping blocks checkout',async()=>{const c=await call('/catalog');assert.equal(c.status,200);assert.deepEqual(c.data.products[0].variants.map(v=>v.price),[9900,17900,39900]);assert.equal((await call('/quote','POST',{items})).status,503);});
test('server owns prices, quantity validation and free-delivery boundaries',()=>{shipping();const q=calculateQuote(db,[{...items[0],price:1,shipping:0}]);assert.equal(q.subtotal,17900);assert.equal(q.shipping,4000);assert.equal(q.total,21900);const s=getSettings(db);s.freeShippingThreshold=35800;db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(s));assert.equal(calculateQuote(db,[{...items[0],qty:2}]).shipping,0);assert.equal(calculateQuote(db,items).shipping,4000);assert.throws(()=>calculateQuote(db,[{...items[0],qty:-1}]));assert.throws(()=>calculateQuote(db,[{...items[0],size:'999'}]));assert.throws(()=>calculateQuote(db,[{...items[0],qty:30},{...items[0],qty:30}]));s.freeShippingThreshold=null;db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(s));assert.equal(calculateQuote(db,[{...items[0],qty:4}]).shipping,16000);s.freeShippingThreshold=59900;db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(s));});
test('invalid totals and customers rejected; COD persisted and idempotent',async()=>{const payload={items,customer,paymentMethod:'cod',expectedTotal:21900};assert.equal((await call('/orders','POST',{...payload,expectedTotal:1},{'Idempotency-Key':'bad-total-1111111111'})).status,409);assert.equal((await call('/orders','POST',{...payload,customer:{...customer,pincode:'000000'}},{'Idempotency-Key':'bad-customer-111111'})).status,400);const a=await call('/orders','POST',payload,{'Idempotency-Key':'cod-order-1111111111'});assert.equal(a.status,201);codOrder=a.data;assert.equal(codOrder.status,'confirmed');const b=await call('/orders','POST',payload,{'Idempotency-Key':'cod-order-1111111111'});assert.equal(b.data.id,codOrder.id);assert.equal(db.prepare('SELECT count(*) AS n FROM orders').get().n,1);assert.equal((await call('/orders','POST',{...payload,customer:{...customer,name:'Someone else'}},{'Idempotency-Key':'cod-order-1111111111'})).status,409);});
test('private order token and same-origin writes enforced',async()=>{assert.equal((await call('/orders/'+codOrder.id)).status,404);assert.equal((await call('/orders/'+codOrder.id,'GET',undefined,{'X-Order-Token':codOrder.accessToken})).status,200);assert.equal((await call('/quote','POST',{items},{Origin:'https://attacker.example'})).status,403);assert.equal((await call('/admin/orders')).status,401);const r=await fetch(base+'/server/app.mjs');assert.equal(r.status,404);const html=await fetch(base+'/');assert.equal(html.status,200);assert.match(await html.text(),/Good things/);});
test('admin authentication, product changes, and delivery state transitions',async()=>{const salt=randomBytes(32).toString('hex'),hash=scryptSync('a-long-test-password',salt,64).toString('hex');db.prepare('INSERT INTO admin VALUES (1,?,?,?)').run('owner@example.com',salt,hash);assert.equal((await call('/admin/login','POST',{email:'owner@example.com',password:'wrong'})).status,401);const login=await call('/admin/login','POST',{email:'owner@example.com',password:'a-long-test-password'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);let r=await call('/admin/orders/'+codOrder.id,'PATCH',{status:'delivered'},{Cookie:cookie});assert.equal(r.status,400);r=await call('/admin/orders/'+codOrder.id,'PATCH',{status:'packed'},{Cookie:cookie});assert.equal(r.status,200);assert.equal((await call('/admin/orders/'+codOrder.id,'PATCH',{status:'shipped'},{Cookie:cookie})).status,400);assert.equal((await call('/admin/orders/'+codOrder.id,'PATCH',{status:'shipped',courier:'Courier',trackingNumber:'ABC123',trackingUrl:'javascript:alert(1)'},{Cookie:cookie})).status,400);r=await call('/admin/orders/'+codOrder.id,'PATCH',{status:'shipped',courier:'Courier',trackingNumber:'ABC123',trackingUrl:'https://example.com/track'},{Cookie:cookie});assert.equal(r.status,200);r=await call('/admin/orders/'+codOrder.id,'PATCH',{status:'delivered',courier:'Courier',trackingNumber:'ABC123'},{Cookie:cookie});assert.equal(r.data.paymentStatus,'paid');const p=(await call('/admin/products','GET',undefined,{Cookie:cookie})).data.products[0];r=await call('/admin/products','POST',{...p,active:false},{Cookie:cookie});assert.equal(r.status,200);assert.equal((await call('/catalog')).data.products.length,2);assert.equal((await call('/quote','POST',{items})).status,400);await call('/admin/products','POST',{...p,revision:r.data.product.revision},{Cookie:cookie});});
test('payment creation reused; forged signature rejected; captured payment verified',async()=>{const created=await call('/orders','POST',{items,customer,paymentMethod:'online',expectedTotal:21900},{'Idempotency-Key':'online-order-1111111'});assert.equal(created.status,201);onlineOrder=created.data;const headers={'X-Order-Token':onlineOrder.accessToken};const [a,b]=await Promise.all([call('/orders/'+onlineOrder.id+'/payment','POST',{},headers),call('/orders/'+onlineOrder.id+'/payment','POST',{},headers)]);assert.equal(a.status,200);assert.equal(a.data.razorpayOrderId,b.data.razorpayOrderId);assert.equal(gatewayCount,1);onlineOrder.razorpayOrderId=a.data.razorpayOrderId;const verify={razorpay_order_id:a.data.razorpayOrderId,razorpay_payment_id:'pay_Test',razorpay_signature:'bad'};assert.equal((await call('/orders/'+onlineOrder.id+'/verify','POST',verify,headers)).status,400);assert.equal((await call('/admin/orders/'+onlineOrder.id,'PATCH',{status:'packed'},{Cookie:cookie})).status,400);verify.razorpay_signature=createHmac('sha256',env.RAZORPAY_KEY_SECRET).update(verify.razorpay_order_id+'|pay_Test').digest('hex');const r=await call('/orders/'+onlineOrder.id+'/verify','POST',verify,headers);assert.equal(r.data.paymentStatus,'paid');assert.equal(r.data.status,'confirmed');});
test('signed webhook is idempotent, rejects amount mismatch, and recovers interrupted checkout',async()=>{const created=await call('/orders','POST',{items,customer,paymentMethod:'online',expectedTotal:21900},{'Idempotency-Key':'webhook-order-111111'});const o=created.data;const p=await call('/orders/'+o.id+'/payment','POST',{}, {'X-Order-Token':o.accessToken});const entity={id:'pay_Webhook',order_id:p.data.razorpayOrderId,amount:21900,currency:'INR',status:'captured'};const event={event:'payment.captured',payload:{payment:{entity}}};const sign=x=>createHmac('sha256',env.RAZORPAY_WEBHOOK_SECRET).update(JSON.stringify(x)).digest('hex');assert.equal((await call('/payments/webhook','POST',event,{'X-Razorpay-Signature':'forged'})).status,400);const bad={...event,payload:{payment:{entity:{...entity,amount:1}}}};assert.equal((await call('/payments/webhook','POST',bad,{'X-Razorpay-Signature':sign(bad),'X-Razorpay-Event-Id':'bad-event'})).status,400);const headers={'X-Razorpay-Signature':sign(event),'X-Razorpay-Event-Id':'captured-event'};assert.equal((await call('/payments/webhook','POST',event,headers)).status,200);assert.equal((await call('/payments/webhook','POST',event,headers)).status,200);const confirmed=await call('/orders/'+o.id,'GET',undefined,{'X-Order-Token':o.accessToken});assert.equal(confirmed.data.paymentStatus,'paid');assert.equal(db.prepare('SELECT count(*) AS n FROM webhook_events').get().n,1);});
test('settings, unavailable payment keys and logout behave correctly',async()=>{const r=await call('/admin/settings','PUT',{...getSettings(db),freeShippingThreshold:0,codEnabled:false,shippingConfigured:true,whatsappNumber:'919663401610'},{Cookie:cookie});assert.equal(r.status,200);assert.equal(calculateQuote(db,items).shipping,0);assert.equal((await call('/orders','POST',{items,customer,paymentMethod:'cod',expectedTotal:17900},{'Idempotency-Key':'disabled-cod-1111111'})).status,400);delete env.RAZORPAY_KEY_SECRET;assert.equal((await call('/catalog')).data.settings.onlineAvailable,false);assert.equal((await call('/orders','POST',{items,customer,paymentMethod:'online',expectedTotal:17900},{'Idempotency-Key':'disabled-online-11111'})).status,503);assert.equal((await call('/admin/logout','POST',{}, {Cookie:cookie})).status,200);assert.equal((await call('/admin/orders','GET',undefined,{Cookie:cookie})).status,401);});
