import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {fixture,customer,items} from './test-fixture.mjs';
import {createApp} from './app.mjs';
import {getProducts,getSettings,getOrder} from './db.mjs';
import {mailWorker} from './mail.mjs';

async function setup(t){const db=fixture(),env={APP_ORIGIN:'http://localhost:3000',RAZORPAY_KEY_ID:'rzp_test_fixture',RAZORPAY_KEY_SECRET:'secret',RAZORPAY_WEBHOOK_SECRET:'webhook'};const {server}=createApp({db,env});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;t.after(async()=>{await new Promise(r=>server.close(r));db.close();});const call=async(path,method='GET',body,headers={})=>{const r=await fetch(base+path,{method,headers:{Origin:env.APP_ORIGIN,'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,data:await r.json()};};const login=await call('/api/admin/login','POST',{email:'owner@example.com',password:'fixture-password-123'}),cookie=login.headers.get('set-cookie').split(';')[0];const order=(patch={},key=randomUUID())=>call('/api/orders','POST',{items,customer,paymentMethod:'cod',expectedTotal:23900,acceptedTerms:true,...patch},{'Idempotency-Key':key});return {db,env,call,order,cookie,base};}
test('stock is reserved once, overselling is blocked, and cancellation restores it once',async t=>{const {db,order,call,cookie}=await setup(t);const p=getProducts(db)[0];p.variants.find(v=>v.size==='150').stock=1;db.prepare('UPDATE products SET data=? WHERE id=?').run(JSON.stringify(p),p.id);const key=randomUUID();const results=await Promise.all([order({},key),order({},key),order()]);assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(results.filter(r=>r.status===409).length,1);assert.equal(getProducts(db)[0].variants[1].stock,0);const o=results.find(r=>r.status===201).data;for(let i=0;i<2;i++)assert.equal((await call('/api/admin/orders/'+o.id,'PATCH',{status:'cancelled'},{Cookie:cookie})).status,200);assert.equal(getProducts(db)[0].variants[1].stock,1);assert.equal(db.prepare('SELECT count(*) n FROM mail_outbox').get().n,4);});
test('delivery, COD fee, terms, and readiness enforced on the server',async t=>{const {db,order,call,cookie}=await setup(t);assert.equal((await order({customer:{...customer,pincode:'110001'}})).status,400);assert.equal((await order({expectedTotal:21900})).status,409);assert.equal((await order({acceptedTerms:false})).status,400);const q=await call('/api/quote','POST',{items,pincode:'576101',paymentMethod:'cod'});assert.equal(q.data.codFee,2000);assert.equal(q.data.total,23900);const s=getSettings(db);assert.equal((await call('/api/admin/settings','PUT',{...s,privacyPolicy:''},{Cookie:cookie})).status,400);assert.equal(getSettings(db).privacyPolicy,s.privacyPolicy);assert.equal((await call('/api/admin/settings','PUT',{...s,shippingConfigured:false,privacyPolicy:''},{Cookie:cookie})).status,200);assert.equal((await order()).status,503);});
test('signed partial/full refunds reconcile without duplicate money or restock; captured replay cannot undo refund',async t=>{const {db,order,call,env,cookie}=await setup(t);const o=(await order({paymentMethod:'online',expectedTotal:21900})).data;db.prepare("UPDATE orders SET payment_status='paid',status='confirmed',razorpay_payment_id='pay_Fixture',razorpay_order_id='order_Fixture' WHERE id=?").run(o.id);const hook=async(event,id)=>call('/api/payments/webhook','POST',event,{'X-Razorpay-Signature':createHmac('sha256',env.RAZORPAY_WEBHOOK_SECRET).update(JSON.stringify(event)).digest('hex'),'X-Razorpay-Event-Id':id});const refund=(id,amount,status='processed')=>({event:'refund.'+status,payload:{refund:{entity:{id,payment_id:'pay_Fixture',amount,status,currency:'INR'}}}});assert.equal((await hook(refund('rfnd_One',10000),'one')).status,200);assert.equal(getOrder(db,o.id).paymentStatus,'partially_refunded');assert.equal((await hook(refund('rfnd_One',10000),'one-repeated')).status,200);assert.equal(getOrder(db,o.id).refundedAmount,10000);assert.equal((await hook(refund('rfnd_Bad',20000),'bad')).status,400);assert.equal(db.prepare("SELECT id FROM refunds WHERE id='rfnd_Bad'").get(),undefined);assert.equal((await hook(refund('rfnd_Two',11900),'two')).status,200);assert.equal(getOrder(db,o.id).paymentStatus,'refunded');assert.equal(getOrder(db,o.id).status,'cancelled');assert.equal(getProducts(db)[0].variants[1].stock,9);const capture={event:'payment.captured',payload:{payment:{entity:{id:'pay_Fixture',order_id:'order_Fixture',amount:21900,currency:'INR',status:'captured'}}}};await hook(capture,'late-capture');assert.equal(getOrder(db,o.id).paymentStatus,'refunded');for(let i=0;i<2;i++)assert.equal((await call('/api/admin/orders/'+o.id+'/restock','POST',{}, {Cookie:cookie})).status,200);assert.equal(getProducts(db)[0].variants[1].stock,10);});
test('email outbox retries failures, keeps customer links private from owner notices, and does not resend successes',async t=>{const {db,order}=await setup(t);await order();let calls=0;const sent=[];const worker=mailWorker(db,{APP_ORIGIN:'https://tea.example.test',MAIL_FROM:'test@example.com'},{sendMail:async message=>{calls++;if(calls===1)throw Error('Temporary failure');sent.push(message);return {rejected:[]};}});t.after(()=>worker.stop());await worker.flush();assert.equal(db.prepare('SELECT count(*) n FROM mail_outbox WHERE sent_at IS NULL').get().n,1);db.prepare('UPDATE mail_outbox SET next_attempt=0').run();await worker.flush();await worker.flush();assert.equal(sent.length,2);assert.ok(sent.find(m=>m.to==='customer@example.com').text.includes('/order.html#'));assert.ok(!sent.find(m=>m.to==='owner@example.com').text.includes('/order.html#'));assert.equal(calls,3);});
test('stale product edits cannot overwrite purchased stock and shipped cancellations need explicit restocking',async t=>{const {db,order,call,cookie}=await setup(t);const p=getProducts(db)[0],o=(await order()).data;assert.equal((await call('/api/admin/products','POST',{...p,variants:p.variants.map(v=>({...v,stock:v.stock??null}))},{Cookie:cookie})).status,409);assert.equal(getProducts(db)[0].variants[1].stock,9);for(const status of ['packed','shipped','cancelled','cancelled'])assert.equal((await call('/api/admin/orders/'+o.id,'PATCH',{status,courier:'Test courier',trackingNumber:'TEST123'},{Cookie:cookie})).status,200);assert.equal(getProducts(db)[0].variants[1].stock,9);assert.equal((await call('/api/admin/orders/'+o.id+'/restock','POST',{}, {Cookie:cookie})).status,200);assert.equal(getProducts(db)[0].variants[1].stock,10);});
