import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {createApp} from '../server/app.mjs';
import {fixture} from '../server/test-fixture.mjs';
const db=fixture(),env={APP_ORIGIN:'http://127.0.0.1'},errors=[];
const gatewayOrders=new Map();let gatewayCount=0;const gatewayFetch=async(url,options)=>{if(url.endsWith('/orders')){const b=JSON.parse(options.body),id='order_Browser'+(++gatewayCount);gatewayOrders.set(id,b);return {ok:true,json:async()=>({id,...b})};}if(url.includes('/payments/')){const id=[...gatewayOrders.keys()].at(-1);return {ok:true,json:async()=>({id:'pay_Browser',order_id:id,amount:gatewayOrders.get(id).amount,currency:'INR',status:'captured'})};}throw Error('Unexpected gateway call');};
const {server}=createApp({db,env,gatewayFetch});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port;env.APP_ORIGIN=base;
// createApp captures the canonical origin at creation; use a second instance on the same port.
const port=server.address().port;await new Promise(r=>server.close(r));const app=createApp({db,env,gatewayFetch});await new Promise(r=>app.server.listen(port,'127.0.0.1',r));
const browser=await chromium.launch();await mkdir('.preview',{recursive:true});
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
 const context=await browser.newContext({viewport});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 for(const route of ['/','/menu.html','/about.html','/contacts.html','/policies.html']){await page.goto(base+route);await page.locator('#business-footer').filter({hasText:'Test Store'}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow: '+route);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],`Accessibility on ${route} at ${viewport.width}`);if(route==='/'){if(viewport.width===390){const card=page.locator('#home-products .product-card').nth(1);await card.scrollIntoViewIfNeeded();await page.waitForFunction(element=>element.classList.contains('is-scroll-active'),await card.elementHandle());assert.match(await card.locator('.product-visual img').evaluate(element=>getComputedStyle(element).transform),/^matrix\(/);}await page.screenshot({path:`.preview/launch-home-${viewport.width}.png`,fullPage:true});}}
 await page.goto(base+'/menu.html');await page.locator('[data-add="ginger"]').click();await page.locator('[data-open-cart]').first().click();await page.getByRole('link',{name:/Continue to checkout/}).click();await page.getByLabel('Full name').fill('Browser Customer');await page.getByLabel('Mobile number').fill('9876543210');await page.getByLabel('Email (optional)').fill('browser@example.com');await page.getByLabel('House / flat, street and area').fill('12 Browser Test Road');await page.getByLabel('City / town').fill('Udupi');await page.getByLabel('State / union territory').selectOption('Karnataka');await page.getByLabel('PIN code').fill('110001');await page.getByLabel('PIN code').blur();await page.getByText('Delivery is not available for this PIN code. Please contact us.').waitFor();assert.ok(await page.locator('#place-order').isDisabled());await page.getByLabel('PIN code').fill('576101');await page.getByLabel('PIN code').blur();await page.getByRole('checkbox').check();await page.getByRole('button',{name:/Place cash on delivery order/}).click();await page.waitForURL(/order.html#/);await page.getByText('Order confirmed',{exact:true}).first().waitFor();assert.ok((await page.locator('#order-content').textContent()).includes('239'));await page.getByRole('button',{name:'Print receipt'}).click();await page.emulateMedia({media:'print'});assert.ok(await page.locator('#printable-receipt').isVisible());await page.emulateMedia({media:'screen'});assert.ok(!(await page.locator('#printable-receipt').isVisible()));
 await page.goto(base+'/admin.html');await page.getByLabel('Email').fill('owner@example.com');await page.getByLabel('Password').fill('fixture-password-123');await page.getByRole('button',{name:/Sign in/}).click();await page.getByRole('button',{name:/Store settings/}).click();await page.getByLabel('Legal business / seller name').waitFor();await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.getByText('Settings saved.',{exact:true}).waitFor();await page.getByRole('button',{name:/Products/}).click();await page.getByRole('button',{name:/Edit tea/}).first().click();await page.getByLabel('Available stock').first().fill('12');await page.getByRole('button',{name:'Save tea',exact:true}).click();await page.getByText('Tea saved.',{exact:true}).waitFor();await context.close();
 }

 const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function fillCheckout(){await page.goto(base+'/menu.html');await page.locator('[data-add="ginger"]').click();await page.goto(base+'/checkout.html');await page.getByLabel('Full name').fill('Payment Browser');await page.getByLabel('Mobile number').fill('9876543210');await page.getByLabel('House / flat, street and area').fill('12 Browser Test Road');await page.getByLabel('City / town').fill('Udupi');await page.getByLabel('State / union territory').selectOption('Karnataka');await page.getByLabel('PIN code').fill('576101');await page.getByLabel('PIN code').blur();await page.getByRole('checkbox').check();}
 await context.route('https://wa.me/**',route=>route.abort());await fillCheckout();await page.locator('#payment-whatsapp').check();const countBefore=db.prepare('SELECT count(*) n FROM orders').get().n;const popupPromise=page.waitForEvent('popup');await page.locator('#place-order').click();const popup=await popupPromise;await popup.close();await page.getByRole('link',{name:/Open WhatsApp to send your order/}).waitFor();assert.equal(db.prepare('SELECT count(*) n FROM orders').get().n,countBefore);
 env.RAZORPAY_KEY_ID='rzp_test_browser';env.RAZORPAY_KEY_SECRET='browser-secret';env.RAZORPAY_WEBHOOK_SECRET='browser-webhook';await page.exposeFunction('fixtureSignature',id=>createHmac('sha256',env.RAZORPAY_KEY_SECRET).update(id+'|pay_Browser').digest('hex'));
 await page.route('https://checkout.razorpay.com/v1/checkout.js',route=>route.fulfill({contentType:'application/javascript',body:`window.Razorpay=class{constructor(options){this.options=options}on(){}open(){if(sessionStorage.getItem('dismiss-payment')){this.options.modal.ondismiss();return;}window.fixtureSignature(this.options.order_id).then(signature=>this.options.handler({razorpay_order_id:this.options.order_id,razorpay_payment_id:'pay_Browser',razorpay_signature:signature}));}};`}));
 await page.evaluate(()=>{localStorage.removeItem('zaman-cart-v2');sessionStorage.setItem('dismiss-payment','1');});await fillCheckout();await page.locator('#payment-online').check();await page.locator('#place-order').click();await page.getByRole('link',{name:/View your order \/ retry payment/}).click();await page.getByRole('button',{name:/Complete payment/}).waitFor();await page.evaluate(()=>sessionStorage.removeItem('dismiss-payment'));await page.getByRole('button',{name:/Complete payment/}).click();await page.getByText('Online payment received',{exact:true}).waitFor();assert.equal(gatewayCount,1);await context.close();
 assert.deepEqual(errors,[]);console.log('Desktop and mobile: public pages, accessibility, delivery rejection, COD purchase, private order status, receipt printing, admin settings, stock editing, WhatsApp handoff, and simulated online dismissal/retry/payment passed.');
}finally{await browser.close();await new Promise(r=>app.server.close(r));db.close();}
