const $ = (q,root=document)=>root.querySelector(q);
const $$ = (q,root=document)=>[...root.querySelectorAll(q)];
const esc = v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v/100);
const icon = name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${{bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>'}[name]}</svg>`;
const page=document.body.dataset.page;
const links=[['home','index.html','Home'],['shop','menu.html','Shop tea'],['about','about.html','Our story'],['contact','contacts.html','Let’s talk']];
const nav=links.map(([id,url,label])=>`<a href="${url}" ${page===id?'aria-current="page"':''}>${label}</a>`).join('');
$('#site-header').innerHTML=`<div class="announcement" id="announcement">TIME IS PRECIOUS · MAKE TIME FOR ZAMAN</div><header class="site-header"><div class="nav-inner wrap"><a class="brand" href="index.html" aria-label="Zaman Tea home"><span class="logo-window"><img src="img/zaman/zaman-logo-white-v2.png" alt="Zaman Tea — Time is precious"></span><span class="brand-word">ZAMAN TEA</span></a><nav class="nav-links" aria-label="Main navigation">${nav}</nav><div class="nav-actions"><button class="cart-trigger" data-open-cart aria-label="Open shopping bag">${icon('bag')}<span class="cart-label">Your bag</span><span class="cart-count" data-cart-count>0</span></button><button class="icon-button menu-toggle" id="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button></div></div><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation">${nav}</nav></header>`;
$('#site-footer').innerHTML=`<footer class="site-footer wrap"><div class="footer-top"><div><p class="eyebrow">ZAMAN TEA · TIME IS PRECIOUS</p><p class="footer-tag">Make time.<br><em>Make tea.</em></p></div><div><h3>TAKE A LOOK</h3><nav class="footer-links" aria-label="Footer navigation"><a href="menu.html">Our teas</a><a href="about.html">Our story</a><a href="contacts.html">Get in touch</a><a href="order.html">Track your order</a><a href="policies.html#shipping">Shipping</a><a href="policies.html#returns">Returns & refunds</a><a href="policies.html#privacy">Privacy</a><a href="policies.html#terms">Terms</a></nav></div><div><h3>LET'S TALK TEA</h3><div class="footer-links"><a data-whatsapp href="contacts.html">Chat on WhatsApp ↗</a><span data-delivery-summary>Check delivery at checkout</span><span id="business-footer"></span><span id="payment-summary"></span></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Zaman Tea. Savour the moment.</span><span>All prices in INR <span aria-hidden="true">·</span> <a href="admin.html">Store management</a></span></div></footer>`;
$('#overlays').innerHTML=`<dialog id="cart-dialog" class="cart-dialog" aria-labelledby="cart-title"><div class="cart-layout"><header class="drawer-header"><h2 id="cart-title">Your tea bag <em data-cart-count>0</em></h2><button class="icon-button" data-close-cart aria-label="Close bag">${icon('close')}</button></header><div class="drawer-body"><div id="cart-progress"></div><div id="cart-items"></div></div><footer class="drawer-footer" id="cart-footer"></footer></div></dialog><dialog id="detail-dialog" class="detail-dialog" aria-label="Tea details"></dialog><div class="toast" id="toast" role="status" aria-live="polite"></div>`;
let catalogue=null, filter='all', toastTimer, quoteVersion=0, checkoutQuote=null, checkoutBusy=false, razorpayPromise, productMotionTimer, productMotionFrame, productMotionCards=[];
let cart=[];
try {cart=JSON.parse(localStorage.getItem('zaman-cart-v2')||'[]');if(!Array.isArray(cart))cart=[];cart=cart.filter(i=>i&&typeof i.productId==='string'&&typeof i.size==='string'&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<=50).slice(0,30);}catch{}
const saveCart=()=>{try{localStorage.setItem('zaman-cart-v2',JSON.stringify(cart));}catch{}};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let d;try{d=await r.json();}catch{throw new Error('The store could not be reached. Please try again.');}if(!r.ok)throw new Error(d.error||'Something went wrong. Please try again.');return d;}
function itemInfo(i){const p=catalogue?.products.find(p=>p.id===i.productId),v=p?.variants.find(v=>v.size===i.size);return p&&v?{...i,name:p.name,image:p.image,price:v.price,shipping:p.shipping}:null;}
function totals(){const items=cart.map(itemInfo).filter(Boolean),subtotal=items.reduce((s,i)=>s+i.price*i.qty,0),threshold=catalogue?.settings.freeShippingThreshold;const shipping=threshold!==null&&threshold!==undefined&&subtotal>=threshold?0:items.reduce((s,i)=>s+i.shipping*i.qty,0);return {items,subtotal,shipping,total:subtotal+shipping};}
function progress(t){if(!catalogue?.settings.shippingConfigured)return '<p class="small-note">Delivery rates are being updated. Please contact us to order.</p>';const threshold=catalogue.settings.freeShippingThreshold;if(threshold===null)return '<p class="small-note">Delivery is calculated per pack and shown below.</p>';const left=Math.max(0,threshold-t.subtotal);return `<div class="shipping-progress">${left?`You’re ${money(left)} away from free delivery.`:'A little extra joy: your delivery is free.'}<div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,threshold?100*t.subtotal/threshold:100)}%"></div></div></div>`;}
function totalHtml(t){const configured=!!t.id||catalogue?.settings.shippingConfigured;return `<div class="totals-row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div class="totals-row"><span>Delivery</span><strong>${configured?(t.shipping?money(t.shipping):'Free'):'Not yet set'}</strong></div>${t.codFee?`<div class="totals-row"><span>Cash on delivery fee</span><strong>${money(t.codFee)}</strong></div>`:''}${t.refundedAmount?`<div class="totals-row"><span>Refunded</span><strong>${money(t.refundedAmount)}</strong></div>`:''}${configured?`<div class="totals-row total"><span>Total</span><strong>${money(t.total)}</strong></div>`:''}`;}
function renderCart(){const t=totals(),count=cart.reduce((s,i)=>s+i.qty,0);$$('[data-cart-count]').forEach(n=>n.textContent=count);if(!catalogue){$('#cart-items').innerHTML='<p class="small-note">Your bag will appear when the collection has loaded.</p>';return;}
$('#cart-progress').innerHTML=cart.length?progress(t):'';
$('#cart-items').innerHTML=t.items.length?t.items.map(i=>`<article class="cart-row"><img src="${esc(i.image)}" alt="${esc(i.name)}"><div><h3>${esc(i.name)}</h3><p>${esc(i.size)}g · ${money(i.price)}</p><div class="quantity"><button data-qty="-1" data-product="${esc(i.productId)}" data-size="${esc(i.size)}" aria-label="Decrease ${esc(i.name)} quantity">−</button><span>${i.qty}</span><button data-qty="1" data-product="${esc(i.productId)}" data-size="${esc(i.size)}" aria-label="Increase ${esc(i.name)} quantity" ${i.qty>=50?'disabled':''}>+</button></div></div><div><strong>${money(i.price*i.qty)}</strong><button class="remove" data-remove="${esc(i.productId)}" data-size="${esc(i.size)}">Remove</button></div></article>`).join(''):'<div class="empty-state"><h2>A good cup<br>starts here.</h2><p>Your bag is waiting for a little flavour.</p><a class="button dark" href="menu.html">Explore our teas ↗</a></div>';
$('#cart-footer').innerHTML=t.items.length?`${totalHtml(t)}<a class="button dark full" href="checkout.html">Continue to checkout ↗</a><p class="small-note">Online payment, cash on delivery or WhatsApp.</p>`:'';
if(page==='checkout')renderCheckout();}
function changed(){saveCart();renderCart();}
function add(productId,size,open=false){const p=catalogue?.products.find(p=>p.id===productId);if(!p||!p.variants.find(v=>v.size===size))return;const existing=cart.find(i=>i.productId===productId&&i.size===size);const variant=p.variants.find(v=>v.size===size);if(!Number.isInteger(variant.stock)||variant.stock<=(existing?.qty||0))return toast('No more packs of this size are currently available.');if(existing){if(existing.qty>=50)return toast('Maximum 50 packs per size. Contact us for larger orders.');existing.qty++;}else cart.push({productId,size,qty:1});changed();toast(`${p.name} added to your bag`);if(open)$('#cart-dialog').showModal();}
function productHtml(p,index){const selected=p.variants.find(v=>v.size==='150'&&v.stock>0)||p.variants.find(v=>v.stock>0)||p.variants[0];return `<article class="product-card" data-id="${esc(p.id)}"><a class="product-visual" style="--tone:${esc(p.color)}" href="menu.html?tea=${encodeURIComponent(p.id)}" data-detail="${esc(p.id)}"><span class="product-index">0${index+1}</span><img src="${esc(p.image)}" alt="${esc(p.name)} original packaging" width="640" height="1280" loading="lazy"><span class="product-notes">${esc(p.notes)}</span></a><div class="product-info"><div class="product-title"><h3>${esc(p.name.replace(/ Tea$/,''))}</h3><span class="price">${money(selected.price)}</span></div><p class="product-description">${esc(p.description)}</p><div class="product-buy"><select class="size-select" aria-label="Pack size for ${esc(p.name)}">${p.variants.map(v=>`<option value="${esc(v.size)}" ${v.size===selected.size?'selected':''}>${esc(v.size)}g</option>`).join('')}</select><button class="add-button" data-add="${esc(p.id)}" ${selected.stock>0?'':'disabled'}>${selected.stock>0?'Add to bag':'Sold out'} <span aria-hidden="true">+</span></button></div><a class="product-detail-link" href="menu.html?tea=${encodeURIComponent(p.id)}" data-detail="${esc(p.id)}">A closer look ↗</a></div></article>`;}
function updateMobileProductMotion(){productMotionFrame=0;if(!productMotionCards.length)return;const viewportCenter=innerHeight/2;for(const [index,card] of productMotionCards.entries()){const rect=card.getBoundingClientRect(),range=(innerHeight+rect.height)/2,progress=Math.max(-1,Math.min(1,(viewportCenter-(rect.top+rect.height/2))/range)),focus=1-Math.abs(progress),baseRotation=index===1?5:-6,image=$('.product-visual img',card);card.classList.add('is-scroll-parallax');image.style.setProperty('--parallax-y',(-focus*16).toFixed(2)+'px');image.style.setProperty('--parallax-rotate',(baseRotation*(1-focus)).toFixed(2)+'deg');image.style.setProperty('--parallax-scale',(1+focus*.065).toFixed(3));}}
function requestProductMotion(){if(productMotionCards.length&&!productMotionFrame)productMotionFrame=requestAnimationFrame(updateMobileProductMotion);}
function setupMobileProductMotion(){const grid=$('#home-products');productMotionCards=[];if(!grid)return;for(const card of $$('.product-card',grid)){card.classList.remove('is-scroll-parallax');const image=$('.product-visual img',card);for(const property of ['--parallax-y','--parallax-rotate','--parallax-scale'])image.style.removeProperty(property);}if(!matchMedia('(max-width: 760px) and (prefers-reduced-motion: no-preference)').matches)return;productMotionCards=$$('.product-card',grid);requestProductMotion();}
function renderProducts(){const products=catalogue.products.filter(p=>filter==='all'||p.id===filter);for(const id of ['home-products','shop-products'])if($('#'+id))$('#'+id).innerHTML=products.length?products.map(productHtml).join(''):'<div class="empty-state"><h2>This tea is taking a pause.</h2><p>Explore another flavour or check back soon.</p></div>';if($('#product-count'))$('#product-count').textContent=`${products.length} ${products.length===1?'blend':'blends'} to savour`;if($('#add-bundle')){const all=['ginger','cardamom','darjeeling'].map(id=>catalogue.products.find(p=>p.id===id)?.variants.find(v=>v.size==='150'));$('#add-bundle').disabled=all.some(v=>!v||!v.stock);$('#bundle-price').textContent=all.every(Boolean)?`· ${money(all.reduce((s,v)=>s+v.price,0))}`:'';}setupMobileProductMotion();}
function showDetail(id){const p=catalogue.products.find(p=>p.id===id);if(!p)return;const v=p.variants.find(v=>v.size==='150')||p.variants[0];$('#detail-dialog').innerHTML=`<div class="detail-grid"><div class="detail-picture" style="background:${esc(p.color)}"><img src="${esc(p.image)}" alt="${esc(p.name)} original packaging"></div><div class="detail-content product-card" data-id="${esc(p.id)}"><div class="drawer-header"><span class="eyebrow">YOUR NEXT GOOD CUP</span><button class="icon-button" data-close-detail aria-label="Close details">${icon('close')}</button></div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><p class="eyebrow detail-notes">${esc(p.notes)}</p><p class="small-note">Available in ${p.variants.map(v=>esc(v.size)+'g').join(', ')}. Choose a pack size below.</p>${[['ingredients','Ingredients'],['brewing','How to brew'],['storage','Storage'],['shelfLife','Shelf life']].filter(([k])=>p[k]).map(([k,label])=>`<div class="product-fact"><h3>${label}</h3><p>${esc(p[k])}</p></div>`).join('')}<div class="product-title detail-price"><strong class="price">${money(v.price)}</strong><span class="small-note">${catalogue.settings.shippingConfigured?`${money(p.shipping)} delivery per pack${catalogue.settings.freeShippingThreshold!==null?`; free from ${money(catalogue.settings.freeShippingThreshold)}`:''}`:'Delivery rates being updated'}</span></div><div class="product-buy"><select class="size-select" aria-label="Pack size">${p.variants.map(s=>`<option value="${esc(s.size)}" ${s.size===v.size?'selected':''}>${esc(s.size)}g</option>`).join('')}</select><button class="add-button" data-add="${esc(p.id)}" ${v.stock>0?'':'disabled'}>${v.stock>0?'Add to bag +':'Sold out'}</button></div></div></div>`;$('#detail-dialog').showModal();}
function whatsapp(message){if(!catalogue?.settings.whatsappNumber)return toast('Please try again once the store has loaded.');window.open(`https://wa.me/${catalogue.settings.whatsappNumber}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
async function load(){try{catalogue=await api('/catalog');const original=cart.length;cart=cart.filter(itemInfo);if(cart.length!==original){saveCart();toast('An unavailable tea was removed from your bag.');}const s=catalogue.settings;renderBusiness(s);$('#announcement').textContent=s.shippingConfigured&&s.freeShippingThreshold!==null?`A LITTLE MORE TEA, DELIVERY ON US · FREE FROM ${money(s.freeShippingThreshold)}`:'TIME IS PRECIOUS · MAKE TIME FOR ZAMAN';$$('[data-whatsapp]').forEach(a=>{a.href=`https://wa.me/${s.whatsappNumber}`;a.target='_blank';a.rel='noopener noreferrer';});if($('#support-number'))$('#support-number').textContent=`WhatsApp: +${s.whatsappNumber}`;renderProducts();renderCart();if(page==='checkout'){setupPaymentOptions();renderCheckout();}if(page==='shop'){const id=new URLSearchParams(location.search).get('tea');if(id)showDetail(id);}if(page==='order')await renderOrder();}catch(e){for(const id of ['home-products','shop-products','order-content'])if($('#'+id))$('#'+id).innerHTML=`<div class="error-panel"><h2>A little pause.</h2><p>${esc(e.message)}</p><button class="button dark" data-retry>Try again</button></div>`;if($('#checkout-message'))$('#checkout-message').textContent=e.message;toast(e.message);}}
function summaryItems(items){return items.map(i=>`<div class="summary-product"><img src="${esc(i.image)}" alt="${esc(i.name)}"><div><h3>${esc(i.name)}</h3><p>${esc(i.size)}g × ${i.qty}</p></div><strong>${money(i.price*i.qty)}</strong></div>`).join('');}
async function renderCheckout(){const t=totals(),version=++quoteVersion;checkoutQuote=null;$('#place-order').disabled=true;$('#checkout-items').innerHTML=t.items.length?summaryItems(t.items):'<div class="empty-state"><p>Your bag is empty.</p><a class="text-link" href="menu.html">Find your flavour ↗</a></div>';$('#checkout-totals').innerHTML=t.items.length?totalHtml(t):'';$('#checkout-shipping-note').textContent=t.items.length?'Delivery is charged per pack. Your final total is checked before your order is placed.':'';if(!t.items.length)return;try{const q=await api('/quote',{method:'POST',body:JSON.stringify({items:cart,pincode:$('#pincode')?.value,paymentMethod:$('input[name=payment]:checked')?.value})});if(version!==quoteVersion)return;checkoutQuote=q;$('#checkout-totals').innerHTML=totalHtml(q);$('#place-order').disabled=checkoutBusy;$('#checkout-message').textContent='';$('#delivery-check').textContent=$('#pincode').value?catalogue.settings.deliverySummary||'Delivery is available for this PIN code.':'Enter your PIN code to check delivery.';}catch(e){if(version===quoteVersion)$('#checkout-message').textContent=e.message;}}
function setupPaymentOptions(){const s=catalogue.settings;$('#payment-online').disabled=!s.onlineAvailable;$('#payment-cod').disabled=!s.codEnabled;$('#payment-whatsapp').disabled=!s.whatsappNumber;if(!s.onlineAvailable)$('#online-description').textContent='Online payments are currently unavailable.';const first=['online','cod','whatsapp'].map(x=>$('#payment-'+x)).find(x=>!x.disabled);if(first)first.checked=true;updateSubmitLabel();}
function updateSubmitLabel(){const method=$('input[name=payment]:checked')?.value;$('#place-order').textContent=method==='online'?'Continue to payment ↗':method==='whatsapp'?'Continue to WhatsApp ↗':'Place cash on delivery order ↗';}
function loadRazorpay(){if(window.Razorpay)return Promise.resolve();if(razorpayPromise)return razorpayPromise;razorpayPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>window.Razorpay?resolve():reject(new Error('Payment checkout could not load.'));script.onerror=()=>{razorpayPromise=null;reject(new Error('Payment checkout could not load. Please check your connection and try again.'));};document.head.appendChild(script);});return razorpayPromise;}
function orderLink(order){return `order.html#${order.id}/${order.accessToken}`;}
function rememberOrder(order){try{localStorage.setItem('zaman-last-order',orderLink(order));}catch{}}
async function pay(order,redirect=true){await loadRazorpay();const data=await api(`/orders/${order.id}/payment`,{method:'POST',headers:{'X-Order-Token':order.accessToken},body:'{}'});if(data.alreadyPaid){location.href=orderLink(order);return;}
await new Promise((resolve,reject)=>{const rz=new window.Razorpay({key:data.keyId,amount:data.amount,currency:'INR',name:'Zaman Tea',description:`Order ${order.number}`,order_id:data.razorpayOrderId,prefill:data.prefill,theme:{color:'#344f32'},modal:{ondismiss:()=>reject(new Error('Payment was not completed. Your order link lets you try again.'))},handler:async result=>{try{const verified=await api(`/orders/${order.id}/verify`,{method:'POST',headers:{'X-Order-Token':order.accessToken},body:JSON.stringify(result)});if(verified.paymentStatus!=='paid')toast('Payment is processing. Your order status will update after confirmation.');if(redirect){cart=[];changed();location.href=orderLink(order);}else await renderOrder();resolve();}catch(e){reject(e);}}});rz.on('payment.failed',()=>toast('Payment failed. Try another method in the payment window.'));rz.open();});}
async function checkout(event){event.preventDefault();if(checkoutBusy||!checkoutQuote||!$('#checkout-form').reportValidity())return;checkoutBusy=true;$('#place-order').disabled=true;$('#checkout-message').textContent='';const formData=new FormData(event.currentTarget),customer=Object.fromEntries(formData);const method=customer.payment;delete customer.payment;delete customer.acceptedTerms;try{const q=await api('/quote',{method:'POST',body:JSON.stringify({items:cart,pincode:$('#pincode')?.value,paymentMethod:$('input[name=payment]:checked')?.value})});if(q.total!==checkoutQuote.total){checkoutQuote=q;$('#checkout-totals').innerHTML=totalHtml(q);throw new Error('Your order total has changed. Please review it, then place your order again.');}await api('/delivery',{method:'POST',body:JSON.stringify({pincode:customer.pincode,paymentMethod:method})});if(method==='whatsapp'){const lines=['Hello Zaman Tea! I would like to order:',...q.items.map(i=>`${i.name} · ${i.size}g × ${i.qty} — ${money(i.price*i.qty)}`),`Subtotal: ${money(q.subtotal)}`,`Delivery: ${money(q.shipping)}`,`Total: ${money(q.total)}`,'',customer.name,customer.phone,customer.email,`${customer.address}, ${customer.city}, ${customer.state} ${customer.pincode}`,customer.notes].filter(Boolean);const url=`https://wa.me/${catalogue.settings.whatsappNumber}?text=${encodeURIComponent(lines.join('\n'))}`;$('#checkout-message').innerHTML=`Your message is ready. <a class="text-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open WhatsApp to send your order ↗</a><br>Your order is confirmed with us in the conversation.`;window.open(url,'_blank','noopener,noreferrer');return;}
let key;try{const fingerprint=JSON.stringify({items:cart,customer,method,total:q.total});const old=JSON.parse(sessionStorage.getItem('zaman-checkout-attempt')||'null');key=old?.fingerprint===fingerprint?old.key:crypto.randomUUID();sessionStorage.setItem('zaman-checkout-attempt',JSON.stringify({fingerprint,key}));}catch{key=crypto.randomUUID();}
const order=await api('/orders',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({items:cart,customer,paymentMethod:method,expectedTotal:q.total,acceptedTerms:true})});rememberOrder(order);if(method==='online'){try{await pay(order);}catch(e){$('#checkout-message').innerHTML=`${esc(e.message)} <a class="text-link" href="${esc(orderLink(order))}">View your order / retry payment ↗</a>`;}}else{cart=[];changed();location.href=orderLink(order);}}catch(e){$('#checkout-message').textContent=e.message;}finally{checkoutBusy=false;$('#place-order').disabled=!checkoutQuote;}}
async function renderOrder(){const [id,token]=location.hash.slice(1).split('/');if(!id||!token){let last;try{last=localStorage.getItem('zaman-last-order');}catch{}$('#order-content').innerHTML=`<h1>Your tea, on its way.</h1><p>Open the private link you received at checkout to see your order.</p>${last?`<a class="button dark" href="${esc(last)}">View your latest order ↗</a>`:''}`;return;}const o=await api(`/orders/${encodeURIComponent(id)}`,{headers:{'X-Order-Token':token}});const names={pending_payment:'Awaiting payment',confirmed:'Order confirmed',packed:'Packed with care',shipped:'On its way',delivered:'Delivered',cancelled:'Cancelled'};const steps=['confirmed','packed','shipped','delivered'],idx=steps.indexOf(o.status);const pending=o.paymentMethod==='online'&&o.paymentStatus==='pending'&&o.status!=='cancelled';$('#order-content').innerHTML=`<p class="eyebrow">${esc(o.number)}</p><h1>${pending?'Your tea is<br><em>one step away.</em>':o.status==='cancelled'?'Order cancelled.':'A good choice.<br><em>A better cup.</em>'}</h1><span class="order-status-label">${esc(names[o.status]||o.status)}</span><p class="small-note">Placed ${new Date(o.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</p>${o.status!=='cancelled'?`<div class="status-steps">${steps.map((s,i)=>`<div class="status-step ${idx>=i?'done':''}">${names[s]}</div>`).join('')}</div>`:''}<div class="form-card"><h2>Order details</h2>${summaryItems(o.items)}${totalHtml(o)}<p class="small-note">${o.paymentMethod==='cod'?`Cash on delivery · ${o.paymentStatus==='paid'?'Paid':'Pay '+money(o.total)+' on arrival'}`:['refunded','partially_refunded'].includes(o.paymentStatus)?'Online payment '+o.paymentStatus.replaceAll('_',' '):o.paymentStatus==='paid'?'Online payment received':'Online payment awaiting confirmation'}</p><div class="tracking-detail"><p><strong>Delivery to</strong></p><p>${esc(o.customer.name)}<br>${esc(o.customer.address)}<br>${esc(o.customer.city)}, ${esc(o.customer.state)} ${esc(o.customer.pincode)}</p>${o.courier?`<p><strong>${esc(o.courier)}</strong> · ${esc(o.trackingNumber||'')}</p>`:''}${o.trackingUrl?`<a class="text-link" href="${esc(o.trackingUrl)}" target="_blank" rel="noopener noreferrer">Track your parcel ↗</a>`:''}</div>${pending?'<button class="button dark full payment-resume" id="retry-payment">Complete payment ↗</button>':''}<p class="form-message" id="order-message" role="status"></p></div><p class="small-note">Keep this private order link to check delivery updates. Anyone with this link can view these order details.</p><div class="order-actions"><button class="button outline" id="print-receipt">Print receipt</button><button class="button outline" id="copy-order-link">Copy order link</button><button class="button outline" id="refresh-order">Refresh status</button><button class="button outline" id="order-support">Ask about this order ↗</button></div>`;
$('#print-receipt').onclick=()=>printReceipt(o);$('#copy-order-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Private order link copied');}catch{$('#order-message').textContent='Copy the URL from your address bar to save this order.';}};$('#refresh-order').onclick=()=>renderOrder().catch(e=>$('#order-message').textContent=e.message);$('#order-support').onclick=()=>whatsapp(`Hello Zaman Tea! I need help with order ${o.number}.`);if($('#retry-payment'))$('#retry-payment').onclick=async e=>{e.currentTarget.disabled=true;try{await pay({...o,accessToken:token},false);}catch(err){$('#order-message').textContent=err.message;if($('#retry-payment'))$('#retry-payment').disabled=false;}};}
document.addEventListener('click',e=>{if(e.target.closest('[data-open-cart]')){$('#cart-dialog').showModal();return;}if(e.target.closest('[data-close-cart]'))$('#cart-dialog').close();if(e.target.closest('[data-close-detail]'))$('#detail-dialog').close();const addBtn=e.target.closest('[data-add]');if(addBtn)add(addBtn.dataset.add,$('.size-select',addBtn.closest('.product-card')).value);const q=e.target.closest('[data-qty]');if(q){const i=cart.find(i=>i.productId===q.dataset.product&&i.size===q.dataset.size);if(i){i.qty=Math.max(0,Math.min(50,i.qty+Number(q.dataset.qty)));cart=cart.filter(i=>i.qty>0);changed();}}const r=e.target.closest('[data-remove]');if(r){cart=cart.filter(i=>!(i.productId===r.dataset.remove&&i.size===r.dataset.size));changed();}const f=e.target.closest('[data-filter]');if(f&&catalogue){filter=f.dataset.filter;$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===f)));renderProducts();}const d=e.target.closest('[data-detail]');if(d&&catalogue){e.preventDefault();showDetail(d.dataset.detail);}if(e.target.closest('[data-retry]'))load();});
document.addEventListener('change',e=>{if(e.target.matches('.size-select')){const card=e.target.closest('.product-card'),p=catalogue.products.find(p=>p.id===card.dataset.id);const v=p.variants.find(v=>v.size===e.target.value);$('.price',card).textContent=money(v.price);const button=$('[data-add]',card);button.disabled=!(v.stock>0);button.textContent=v.stock>0?'Add to bag +':'Sold out';}if(e.target.name==='payment'){updateSubmitLabel();renderCheckout();}if(e.target.id==='pincode')renderCheckout();});
$('#menu-toggle').onclick=()=>{const open=$('#mobile-nav').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));$('#menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#mobile-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}});
for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const rect=d.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)d.close();}});
if($('#add-bundle'))$('#add-bundle').onclick=()=>{for(const id of ['ginger','cardamom','darjeeling'])add(id,'150');toast('The tasting trio is in your bag');$('#cart-dialog').showModal();};
if($('#checkout-form')){$('#checkout-form').onsubmit=checkout;const states=['Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'];$('#state').insertAdjacentHTML('beforeend',states.map(s=>`<option>${s}</option>`).join(''));}
if($('#contact-form'))$('#contact-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);whatsapp(`Hello Zaman Tea! My name is ${d.get('name')}.\n\n${d.get('message')}`);$('#contact-status').textContent='Send the prepared message in WhatsApp to reach us.';};
window.addEventListener('storage',e=>{if(e.key==='zaman-cart-v2'){try{const c=JSON.parse(e.newValue||'[]');if(Array.isArray(c))cart=c.filter(i=>i&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<=50&&itemInfo(i));renderCart();}catch{}}});
window.addEventListener('scroll',requestProductMotion,{passive:true});
window.addEventListener('resize',()=>{clearTimeout(productMotionTimer);productMotionTimer=setTimeout(setupMobileProductMotion,150);});
window.addEventListener('hashchange',()=>{if(page==='order')renderOrder().catch(e=>toast(e.message));});
renderCart();load();

function renderBusiness(s){
 $$('[data-delivery-summary]').forEach(e=>e.textContent=s.deliverySummary||'Check delivery at checkout');
 $('#payment-summary').textContent=[s.onlineAvailable?'Online payments':null,s.codEnabled?'Cash on delivery':null,'WhatsApp'].filter(Boolean).join(' · ');
 $('#business-footer').textContent=s.businessName||'';
 if(page==='contact'){const content=document.createElement('div');content.className='business-details';content.innerHTML=`${s.businessName?`<h3>${esc(s.businessName)}</h3>`:''}${s.businessAddress?`<p>${esc(s.businessAddress)}</p>`:''}${s.supportEmail?`<a href="mailto:${esc(s.supportEmail)}">${esc(s.supportEmail)}</a>`:''}${s.supportHours?`<p>Support: ${esc(s.supportHours)}</p>`:''}`;$('.contact-copy').append(content);}
 if(page==='policies')$('#policy-content').innerHTML=s.policiesReviewed?[['shipping','Shipping & delivery','shippingPolicy'],['returns','Cancellations, returns & refunds','returnsPolicy'],['privacy','Your privacy','privacyPolicy'],['terms','Purchase terms','termsPolicy']].map(([id,title,key])=>`<section id="${id}" class="policy-section"><h2>${title}</h2><div class="policy-text">${esc(s[key])}</div></section>`).join(''):`<p>Our customer policies are being finalized. Ordering is paused until they are ready. Please contact us with any questions.</p>`;
}
function printReceipt(o){
 let receipt=$('#printable-receipt');if(!receipt){receipt=document.createElement('section');receipt.id='printable-receipt';document.body.append(receipt);}
 receipt.innerHTML=`<h1>Order receipt</h1><h2>${esc(o.seller?.name||'Zaman Tea')}</h2><p>${esc(o.seller?.address||'')}</p><p>${esc(o.seller?.email||'')}</p><p>${esc(o.number)} · ${new Date(o.createdAt).toLocaleDateString('en-IN')}</p><p>${esc(o.customer.name)}<br>${esc(o.customer.address)}<br>${esc(o.customer.city)}, ${esc(o.customer.state)} ${esc(o.customer.pincode)}</p><table><thead><tr><th>Item</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>${o.items.map(i=>`<tr><td>${esc(i.name)} ${esc(i.size)}g</td><td>${i.qty}</td><td>${money(i.price*i.qty)}</td></tr>`).join('')}</tbody></table><p>Delivery: ${money(o.shipping)}</p><p>COD fee: ${money(o.codFee||0)}</p><strong>Total: ${money(o.total)}</strong><p>Payment: ${esc(o.paymentStatus.replaceAll('_',' '))}</p>${o.refundedAmount?`<p>Refunded: ${money(o.refundedAmount)}</p>`:''}<p>This is an order receipt, not a tax invoice. Contact the seller for a tax invoice if applicable.</p>`;
 window.print();
}
